apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: {{.Values.deploy.replicas}}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: {{.Values.deploy.image.repo}}:{{.Values.deploy.image.tag}}
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 3000
          protocol: TCP
      imagePullSecrets:
      - name: regsecret

